BEGIN;
TRUNCATE "twitter_query", "pages_page", "pages_link", "blog_blogpost", "django_comment_flags", "blog_blogcategory", "galleries_galleryimage", "django_redirect", "conf_setting", "django_content_type", "forms_field", "generic_threadedcomment", "pages_richtextpage", "generic_assignedkeyword", "forms_form", "django_admin_log", "generic_keyword", "django_session", "core_sitepermission_sites", "generic_rating", "auth_group", "core_sitepermission", "galleries_gallery", "django_site", "blog_blogpost_related_posts", "auth_user_user_permissions", "twitter_tweet", "blog_blogpost_categories", "auth_user", "auth_group_permissions", "auth_permission", "forms_fieldentry", "django_comments", "forms_formentry", "auth_user_groups";
SELECT setval(pg_get_serial_sequence('"auth_permission"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"auth_group"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"auth_user"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"django_content_type"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"django_redirect"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"django_site"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"conf_setting"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"core_sitepermission"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"generic_keyword"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"generic_assignedkeyword"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"generic_rating"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"pages_page"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"blog_blogpost"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"blog_blogcategory"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"forms_field"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"forms_formentry"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"forms_fieldentry"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"galleries_galleryimage"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"twitter_query"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"twitter_tweet"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"django_admin_log"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"django_comments"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"django_comment_flags"','id'), 1, false);
COMMIT;
